### ISSUE TITLE
issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by Kohki-Takatama** [Kohki-Takatama/holiday_checkin#11]
# 概要
MVPリリースに必要な機能を作成します。

# 実装予定の機能
- [ ] ユーザー登録
- [ ] ログイン
- [ ] ログアウト
- [ ] やること宣言（投稿）機能
- [ ] みんなの宣言閲覧機能
- [ ] フッター

# 必要なページ

- [ ] static_pages/top
- [ ] user_settions/new
ログイン画面
- [ ] users/new
ユーザー登録画面
- [ ] posts/new
わたしの宣言 作成画面
- [ ] posts/show
わたしの宣言
- [ ] posts/index
みんなの宣言
- [ ] users/edit
設定

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントになります。

- デプロイ、rails newなどのカードも作成しましょう。
- 外部APIや技術に関して調査するものがあれば、それもカードを用意しましょう。

また、作成、編集、削除の機能を1つのissueにまとまっているものがあると思うので、こちらは各機能を1つずつのissueに分解し、ストーリポーイントを5以下（2~3が望ましい）になるように修正してみてください。

上記の観点も踏まえて再度、ご確認をお願いします。

**Comment by Kohki-Takatama** [comment]
レビューありがとうございます。
以下の変更を行いました。ご確認をお願いいたします。

- 外部API：本リリースの機能のためdraftの状態で追加
- Userモデル作成のストーリーポイントを8から5に変更
  - gem deviceに初めて触れるため、余裕を持ってストーリーポイントを8にしていました。
  - migration / controller / view / modelのイメージはついているため、5にします。
  - Userモデル作成・登録機能作成については、個人的には不可分の実装であり、実装に問題がないかの確認もこの２点を通して行えると考えるため、１つのissueに設定しています。
  - ログイン機能のissueから、ログアウト機能のissueを分割しました

**Comment by kenchasonakai** [comment]
LGTMです！
